import type { SelectOption } from '@/components/atoms';

import type { PlaqadProduct } from './plaqad';
import operationDescriptions from './plaqad-operation-descriptions.json';

/**
 * Product-owned operation registry used by the feature authoring UI.
 *
 * Synced on 2026-08-31 from Plaqad Auth's reviewed plan catalogue and Intel's
 * production feature catalogue. Empty products have no reviewed operation
 * manifest yet; the UI reports that explicitly instead of accepting free text.
 */
export const PLAQAD_OPERATION_KEYS_BY_PRODUCT: Record<PlaqadProduct, readonly string[]> = {
	iq: ['chat_turn', 'clarification', 'report_run', 'scheduled_report'],
	ba: [],
	studio: [
		'ai_generation',
		'image_generation',
		'text_to_speech',
		'video_generation',
		'web_search',
		'research_run',
		'email_send',
		'document_export',
		'social_publish',
	],
	os: ['chat', 'index', 'markdown', 'llama_caption', 'vector_upsert', 'vector_delete', 'embedding'],
	pa: ['agent_turn', 'voice_turn', 'browser_action', 'sandbox_run', 'memory_query', 'social_publish', 'workflow_run', 'channel_connector'],
	talent: [
		'chat_completion',
		'cv_parse',
		'whereby_room',
		'jitsi_room',
		'email_transactional',
		'email_security',
		'semantic_rescore',
		'verification_agent',
	],
	intel: [
		'listening_usage',
		'workspace_credits_view',
		'ai_invoke',
		'assistant_chat',
		'assistant_action',
		'suggest_listeners_setup',
		'listener_suggestions',
		'competitor_suggestions',
		'custom_tool_build',
		'custom_tool_run',
		'listener_subscribe',
		'listener_subscriptions_read',
		'listener_unsubscribe',
		'listener_overlay_update',
		'listener_status_update',
		'entities_read',
		'entities_write',
		'entity_read',
		'entity_update',
		'entity_delete',
		'backfill_start',
		'backfill_status',
		'backfill_delete',
		'source_gdelt_news',
		'firecrawl:news',
		'source_rss_news',
		'source_reddit',
		'source_youtube',
		'apify:twitter',
		'apify:instagram',
		'apify:facebook',
		'apify:linkedin',
		'apify:tiktok',
		'app_review_ingest',
		'enrich',
		'relevance_analysis',
		'sentiment_analysis',
		'intent_analysis',
		'topic_entity_analysis',
		'semantic_search',
		'mention_translate',
		'mention_refresh',
		'data_audit',
		'data_audit_detail',
		'rejected_mentions',
		'mention_feedback',
		'correction_stats',
		'data_coverage',
		'stories',
		'story_feed',
		'campaign_management',
		'campaign_attribution',
		'campaign_analytics',
		'campaign_report',
		'alerts',
		'alert_status_update',
		'alert_volume_spike',
		'alert_sentiment_drop',
		'alert_vip_mention',
		'alert_keyword',
		'alert_story_threshold',
		'scct',
		'crisis_score',
		'escalation_routing',
		'war_rooms',
		'push_subscribe',
		'digest',
		'send_daily_digest',
		'synthesize',
		'generate_brief',
		'generate_report',
		'report_templates',
		'report_export',
		'dashboard_stats',
		'period_stats',
		'mention_breakdown',
		'share_of_voice',
		'listener_buckets_save',
		'listener_buckets_suggest',
		'team_departments',
		'dashboard_sharing',
		'public_api_request',
		'api_key_management',
		'max_brand_listeners',
		'max_competitors_per_listener',
		'max_backfill_days',
		'backfill_window_days',
		'ingest_interval_minutes',
		'social_cadence',
		'competitor_social_cadence',
		'social_live_item_cap',
		'alert_interval_minutes',
		'alert_cooldown_hours',
		'alert_thresholds',
		'brief_schedule',
		'digest_frequency',
		'engagement_refresh_policy',
		'enrichment_batch_size',
		'assistant_rate_policy',
		'tool_rate_policy',
		'public_api_rate_policy',
	],
	scout: [],
	people: [],
	maestro: [
		'agent_step',
		'cheap',
		'frontier',
		'image_gen',
		'tts_gen',
		'pdf_render',
		'video_generation',
		'web_search',
		'web_scrape',
		'newsletter_send',
		'embedding',
	],
};

export const PLAQAD_OPERATION_DESCRIPTIONS_BY_PRODUCT = operationDescriptions as Record<PlaqadProduct, Record<string, string>>;

export const getPlaqadOperationOptions = (product: string): SelectOption[] => {
	if (!(product in PLAQAD_OPERATION_KEYS_BY_PRODUCT)) return [];

	const operationKeys = PLAQAD_OPERATION_KEYS_BY_PRODUCT[product as PlaqadProduct];
	const descriptions = PLAQAD_OPERATION_DESCRIPTIONS_BY_PRODUCT[product as PlaqadProduct];

	return operationKeys.map((operation) => ({
		value: operation,
		label: operation,
		description: descriptions[operation],
		supportingText: `plaqad:${product}:${operation}`,
	}));
};
